name: Downstream Backport Helper
description: GitHub Action that links upstream Pull Requests with downstream backport

branding:
  icon: git-branch
  color: green

inputs:
  config-path:
    required: false
    default: .github/downstream-backport-helper.yml
    description: Path to configuration file

  token:
    required: true
    description: GitHub TOKEN or PAT

runs:
  using: node20
  main: dist/index.js
